config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/restaurants", to: "restaurants#index"
  # get "/restaurants/new", to: "restaurants#new"
  # post "/restaurants", to: "restaurants#create"
  # get "/restaurants/:id/edit", to: "restaurants#edit", as: "edit_restaurant"
  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"
  # patch "/restaurants/:id", to: "restaurants#update"
  # delete "/restaurants/:id", to: "restaurants#destroy"
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :stars, collection: (0..5).to_a %>
  <%= f.input :address %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>All restaurants</h1>

      <ul>
        <% @restaurants.each do |restaurant| %>
          <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Add a new restaurant</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h3>Details</h3>
<ul>
  <li>Rating: <%= "⭐️" * @restaurant.stars %></li>
  <li>Address: <%= @restaurant.address %></li>
</ul>

<%= link_to "Update restaurant", edit_restaurant_path(@restaurant) %>
<%= link_to "Destroy restaurant", restaurant_path(@restaurant), method: "delete", data: { confirm: "Are you sure?"} %>
<hr>
<%= link_to "Go back to restaurants list", restaurants_path %>